### ISSUE TITLE
Crew Corner Tab for non-logged in Guest - link to login doesn't work.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#230] opened 2015-08-27 19:25 UTC
As a non logged in visitor to VMS I open a Work Party to look at the details.  Click on the Crew Corner Tab and there is a message that i must be part of the crew and have an account to see the Crew Corner.  There is a link "Sign In To My Backpack" but this is "grayed out".  Seems like this link should be live.
![crewcornertablogin](https://cloud.githubusercontent.com/assets/8312206/9530769/a5f7e196-4cb6-11e5-84d9-f20c42e40740.JPG)

**Comment by chrisrossi** [comment] 2015-08-27 19:32
Duplicate of #227

**Closed** 2015-08-27 23:55 UTC
Labels: Bug, High Priority, Pyramid
