### ISSUE TITLE
VMS: Friends and family sign ups are registered with the same role as the main person.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#350] opened 2015-10-26 18:21 UTC
When an assistant crew leader registers with a +1, the additional family/friends are also showing up as assistant crew leaders. This is not acceptable. See this work party for example. I signed myself up as an ACL, and also signed up a youth, Little Jimmy. Little Jimmy is showing up as an ACL in the work party roster. 

Also, if the friend or family doesn't have the required ACL certifications then the registration is blocked as reported:

When registering as an ACL for a BCRT, I (Seymour Mountains) was not able to register with a spouse. It kept telling me I was missing my First Aid cert, when I have one. I think it was because I was trying to register my spouse, Cass Cade-Mountains too. She does not have the first aid cert, is not an ACL, and was not up until now, not in SF as a contact.

**Comment by davisagli** [comment] 2015-10-26 18:25
I think this is a duplicate of the second part of #79.

**Comment by davisagli** [comment] 2015-10-27 22:59
Closing this as a duplicate

**Closed by davisagli** 2015-10-27 22:59 UTC
Labels: Bug, High Priority, Pyramid, VMS BUDGET
