### ISSUE TITLE
Crew Corner Email message format to Crew

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#236] opened 2015-09-01 18:08 UTC
Here is my feedback about this feature:
1.  I was able to input my own subject line. It did not show the work party name or URL when I received an email. I think it is important for the subject line to include the work party name and start date. I also think it's nice for the crew leader to be able to customize the subject. Would this be feasible:
    * For email: Auto-append the Work Party Name and Start Date to the Subject line. If the crew leader has specified a subject line, insert that text following the Work Party Name and Date. Example: As a crew leader, I type in "Meeting location update" as the Subject line. Then the email that is received would say: "WTA Liberty Lake Trails - Sep 12: Meeting location update
    * In Crew Corner, it would display the custom Subject entered by the Crew Leader (as it does now) but suppress the auto-text since it would be redundant.
2.  The email should automatically include a link to the work party and it would also be nice if the email auto-inserts a signature that is the same as Crew Corner. This could go like this. (Other option could be to put in in a sentence like "Use this link to access more information about this work party.)
Rebecca Lavigne - Crew Leader
Klickitat Trail Backcountry Response Team
3.  I changed my VMS permissions to Admin but my message is still showing in Crew Corner as "Crew Leader." Maybe Salesforce changes haven't shown in VMS yet? Tried to create a new work party to test but wasn't working - assume there is work in progress...
-Rebecca

**Comment by cewing** [comment] 2015-11-10 01:07
@ebskopin can you answer a few questions about this issue:

1.  We believe that the work to auto-append the work party name and date to the subject has already been completed, can you confirm whether that is true or not?
2.  I intend to add a signature to the bottom of a message sent that looks like this:

    [Sender Name] - [Sender Role]
    [WP Name] ([wp url])

  Is that acceptable?

3. With regard to the final bullet point above, It should be noted that the 'role' recorded when a user creates a message is the role that will continue to be displayed for that user on the message board.  If the user later updates their role in the system (or with respect to the work party) this will not change the role recorded with previously sent messages, though new messages should display the new role.  It is also true that you must log out of VMS and then log back in to pick up changes made in your VMS role

Can you confirm that there is in fact an issue for bullet 3 above?

**Comment by cewing** [comment] 2015-11-10 02:00
There are some interesting issues involved in this one.

1.  It appears that the subject and body of the email message sent are stored in SF as they are sent, which means that the enhanced subject and body are stored with the extra information we generate (the name/date in the subj and the signature/url in the body).  
2.  Because of this, when we go to display messages later, they appear with this extra material in them.

I don't think this can be fixed in Pyramid alone, @mscholtz, @davisagli because the actual contruction of the email and what is sent to users and what is stored is done in the custom SF webservice `emailparticipants`.  We could do as desired by adding a few extra fields to the data sent to that service.  If there were a `subject_prefix` and `body_signature` field available, and if the custom web service were to prepend the `subject_prefix` to the subject when sending (but not prepend it when storing) and append the `body_signature` when sending (but not when storing), then this could work as described above.

**Comment by davisagli** [comment] 2015-11-10 02:16
I think we should either not worry about the work party name and date being included in the subject when shown on the message board (I'd argue we should show the subject as it was sent), or we should just do a string replace to remove them as they're displayed. Changing how the API for sending a message works feels like overkill for this.

**Comment by ebskopin** [comment] 2015-11-10 19:46
Hey Cris,

In answer to your questions.

1. In testing this I am not seeing the auto-append of the work party name and date to the subject line in the e-mail.  I would vote for not displaying the work party name and date on the message board.

2. Yes, that should work.

3. It sounds like, as long as the new role is represented when new posts are made, that is fine. I understand that it won't be feasible to change the role listed under past posts.

Thanks.

**Comment by cewing** [comment] 2015-11-10 20:06
@davisagli, @ebskopin,

Thanks for your feedback on this.

I have placed square brackets around the WP name and start date in the subject, following the mailing list tradition of marking messages from a given list in this manner.  That makes it easy enough to post-facto remove this text for display in VMS and still leaves the actual marker in place so you can filter on it in the SF UI if you wanted to.  

I will append the signature as shown, and stop then automatically adding a redundant signature in the VMS display.  We don't get HTML formatting, so the signature will not be bold, but that's okay.  I can also remove the link to the workparty from VMS display, since it won't format as a link and becomes redundant noise in that context.

**Comment by mscholtz** [comment] 2015-11-10 20:18
FWIW I agree w/ David that we should just show the email subject and body in both SF and Pyramid exactly how it was sent.  It's not needed in SF, since every message is linked relationally to a WP record, but it doesn't hurt and gives an accurate representation of what the users saw.

**Comment by cewing** [comment] 2015-11-10 21:49
@mscholtz, as the current webservice stands, we cannot prepend the requested text to the subject in Pyramid and not show it in SF.  I can remove it from the subject as displayed in Pyramid, but if I put it in the subject in Pyramid, and we send the message to the SF webservice with that text in the subject, it will appear in SF.  

Are we now saying, @davisagli, @mscholtz that we should **not** add this text to the subject of the message?  @ebskopin is that acceptable?  

As far as I can tell, there is no way to have the [WP Name, Start Date] text added to the subject of the sent email without storing it as part of the subject unless that is done in the SF webservice.

**Comment by ebskopin** [comment] 2015-11-10 22:23
It is important that the info be in the subject line and if that means it is also stored in the SF webservice then that is fine.

**Comment by mscholtz** [comment] 2015-11-10 23:12
@cewing I was saying the opposite of that.  I was trying to say that I think it's fine if all of that stuff is in the subject of the message everywhere, and we shouldn't expend any effort to prevent it.

**Comment by cewing** [comment] 2015-11-10 23:16
Ahhhhhhhh,  I get it @mscholtz.  Sorry for the misunderstanding.  @ebskopin, is it alright if the text is left in the message subject when displayed in VMS?

**Comment by ebskopin** [comment] 2015-11-10 23:23
Yes.  Sounds like that will be necessary so it's ok for the text to display in VMS.

**Comment by ebskopin** [comment] 2015-11-17 19:59
working as intended. thanks.

**Closed** 2015-11-17 20:27 UTC
Labels: Enhancement, Medium Priority, Pyramid, Reviewing, VMS BUDGET
