### ISSUE TITLE
VMS: Work Party Summary report should defalt to "draft" status

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#514] opened 2016-01-06 20:46 UTC
When the CL goes to the Reports tab and clicks on Edit for the first time the Summary Report status is set to "Published" .  In this state the fields to Message to Crew are hidden.

The Status needs to default to "Draft" until the summary report is set to Published.

**Comment by davisagli** [comment] 2016-01-06 20:48
Closing this as a duplicate of #481 (see the last comment there)

**Closed by davisagli** 2016-01-06 20:48 UTC
Labels: Bug, High Priority, Pyramid, VMS BUDGET
