### ISSUE TITLE
Automatic ACL designation in friends/family registration, only if they have ACL/CL flag

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#79] opened 2015-04-21 18:57 UTC
If I sign someone else up as friends/family:
The registration webservice needs to set the additional registration's role to ACL if the matched contact has a permission level of ACL or CL (or staff?)

@WaBirder57 FYI

**Comment by WaBirder57** [comment] 2015-06-11 21:14
If the matched contact is not an ACL/CL this registered individual (the friend/family) should have the WP role set to Volunteer (regardless of the value for the person entering the registration.

**Comment by davisagli** [comment] 2015-10-26 18:29
I'm changing this one to "high priority" since it's come up a few times and Charlie used the words "not acceptable" in #350

**Comment by mscholtz** [comment] 2015-10-29 00:25
I thought the friends/family were getting Vol role now, but apparently not.

**Comment by WaBirder57** [comment] 2015-10-29 00:59
Matthew,  any volunteer who is an ACL and joins a work party is an ACL role unless they opt out of that role.  We discourage that but give them an option. 


This ticket describes the problem that if an ACL registers for a WP and then signs up one or more friend or family,  all of those individuals are also registered as an ACL even if the don't have that qualification.  It seems like the role of the person registering is impossed on all the friends and family signed up at that time. 


Of course if we can determine that a friend or family person happens to be and ACL then they should get that role but we don't want unqualified folks getting the ACL role. 


Try to reproduce this issue and let me know if you have questions. 



Sent by Outlook for Android



From: Matthew Scholtz

Sent: Wednesday, October 28, 5:25 PM

Subject: Re: [vms] Automatic ACL designation in friends/family registration, only if they have ACL/CL flag (#79)

To: washingtontrails/vms

Cc: Charles Kahle



I thought the friends/family were getting Vol role now, but apparently not.

**Comment by mscholtz** [comment] 2015-10-29 05:04
Hey @WaBirder57 yes, I understood the issue.  Was just trying to express that I think it used to work differently in the past.  In any case, I trust your account of how it works now and we will address it.

**Comment by mscholtz** [comment] 2015-11-02 20:29
@ninetaLogik can you work on this one?  Please read all the comments, and let me know if you have questions.

**Comment by ninetaLogik** [comment] 2015-11-04 18:17
I see 2 options here:
1. Set the WP Reg Role for all FF to Volunteer. 
2. Change the ContactFinderCreator to return the ACL and CL flags so we can determine exactly what the FF is.
@mscholtz which one makes more sense?

**Comment by mscholtz** [comment] 2015-11-04 18:21
@ninetaLogik we definitely need # 2.  # 1 would not satisfy the requirements of this ticket.

**Comment by ninetaLogik** [comment] 2015-11-04 18:57
This should be fixed now.

**Comment by mscholtz** [comment] 2015-11-04 19:23
Thanks, Nineta!

On Wed, Nov 4, 2015 at 10:57 AM, ninetaLogik <notifications@github.com>
wrote:

> This should be fixed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/79#issuecomment-153830378>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by mscholtz** [comment] 2015-11-06 22:07
@ebskopin one thing I realize I'm not sure about is the following edge case:

What if I'm not an ACL, but I sign myself and my wife up for a WP, and my wife is an ACL.  Should she get ACL role?  Or not?  (We do give it to her if she registers herself, just wondering if it's any different if I register her.)

**Comment by ebskopin** [comment] 2015-11-09 22:21
I would say in that, and most cases, the person being signed up should get the ACL role. I would imagine that such instances would be very rare.

**Comment by mscholtz** [comment] 2015-11-10 23:28
OK, we're going to leave this as-is for now, then.

**Comment by ebskopin** [comment] 2015-12-01 20:14
this works.

**Closed by ebskopin** 2015-12-01 20:14 UTC
Labels: High Priority, Reviewing, Salesforce, VMS BUDGET
