### ISSUE TITLE
VMS: Payment not provided WP registration doesn't time out in SF - user can't try again.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#345] opened 2015-10-23 17:29 UTC
What a volunteer signs up for a Work Party which requires a payment.  On the Payment screen if they do not complete the form in the time period provided  they are given a button to "Try Again".  However the SF Registration record still has a status of "Payment Not Provided" and when they click the Try Again button they are taken to the Registration page but now get an error "Contact already has a registration for this work party".

I think the SF registration record status should change to "Canceled" so that the user is able to try registering again.

**Comment by davisagli** [comment] 2015-10-23 19:46
Actually we should leave it as "Payment Not Provided" -- so you can tell that that's what happened -- but treat it the same as Canceled.

**Comment by WaBirder57** [comment] 2015-10-23 19:55
Yes, that would work, I think.

**Comment by cewing** [comment] 2015-10-23 20:43
I'll pick this one up and work on it.

**Comment by cewing** [comment] 2015-10-24 00:28
I am unable to reproduce this behavior, even though yesterday I saw it myself.  

As things stand on master now, when the payment form times out, an AJAX request is sent to `/workparty/<wp_id>/cancel`.  That view updates the status of the registration of the current user in the identified workparty to **Cancelled**.  Then when the user clicks on "Try again" they end up at the registration form and are able to proceed as expected.  I've tried it three times now and it works every time.  I'm not sure what changed because I did see this behavior yesterday.  

I did manually cause the error to occur by changing the status of one of my registrations to `"Payment Not Provided"`.  This does in fact cause the registration to fail as expected.  The error raised comes from the `createregistration` webservice in Salesforce.  I do not believe that we can change how this works from inside the VMS app.  It needs to be dealt with in the Salesforce webservice.

@davisagli do we have the ability to update those webservices to allow new registrations to be created when an existing registration has a status of `"Payment Not Provided"`?  Or is this something that percolator needs to deal with?

**Comment by cewing** [comment] 2015-10-24 00:32
I'm removing the "pyramid" tag from this issue, as it appears to be a problem that can only be solved from within Salesforce

**Comment by mscholtz** [comment] 2015-11-02 21:01
@davisagli @cewing do we want to create a new registration in this case?  Or change the status of the existing one?  When they click "try again", does pyramid know the ID of their existing registration?

**Comment by davisagli** [comment] 2015-11-02 21:03
I don't think it matters from the Pyramid side. When you try again it uses the registration webservice the same as it did the first time; no registration id is retained.

**Comment by mscholtz** [comment] 2015-11-02 23:37
@ninetaLogik can you take this on?  It just needs to omit registrations w/ status "Payment Provided" when it's checking for an existing registration, as well as those w/ "Cancelled".

@cewing I think you still have something to do on your end once that's done, since it looks like it's changing it to Cancelled when it didn't used to.  So sounds like that needs to be reversed.

**Comment by davisagli** [comment] 2015-11-03 00:53
>  It just needs to omit registrations w/ status "Payment Provided" when it's checking for an existing registration, as well as those w/ "Cancelled".

No! It should omit "Payment Not Provided", not "Payment Provided"

**Comment by mscholtz** [comment] 2015-11-03 01:29
That's what I meant.  There is no "Payment Provided" status..

**Comment by ninetaLogik** [comment] 2015-11-04 16:14
This should be fixed now.

**Comment by mscholtz** [comment] 2015-11-04 18:39
@ninetaLogik FYI Charlie is on vacation for an entire month, starting yesterday.  So for the month of Nov we should assign to Elliot to review.

**Comment by mscholtz** [comment] 2015-11-04 18:40
Actually not ready for review yet.  @cewing back to you to make the changes so this doesn't get set to Cancelled.

**Comment by cewing** [comment] 2015-11-04 19:32
Okay, recommencing work.

**Comment by cewing** [comment] 2015-11-05 01:45
This is now ready for review, deployment is running as I type this message.

**Comment by ebskopin** [comment] 2015-12-01 20:50
This works.

**Closed by ebskopin** 2015-12-01 20:50 UTC
Labels: Bug, High Priority, Pyramid, Reviewing, Salesforce, VMS BUDGET
