### ISSUE TITLE
pyramid app is changing names of contacts in some circumstances

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#319] opened 2015-10-14 20:47 UTC
placeholder for now, circumstances still under investigation
Ethan Scholtz used to be Jerome Scholtz used to be Matthew Scholtz

**Comment by davisagli** [comment] 2015-10-14 20:52
Are you entering a new name into the registration form while logged in as an existing contact?

**Comment by mscholtz** [comment] 2015-10-14 21:25
95% sure that's not it.

**Comment by davisagli** [comment] 2016-01-14 23:27
Closing this since it's not actionable. Please reopen with info on how to reproduce the issue if you encounter it again.

**Closed by davisagli** 2016-01-14 23:27 UTC
Labels: Bug, Salesforce, VMS BUDGET
