### ISSUE TITLE
Work party signups for firends should be limited to 6

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#76] opened 2015-04-07 23:40 UTC
When signing up for a work party and adding names to "Bringing someone with you" this should only allow 6 names to be added.  Currently there doesn't seem to be a limit to how many names can be added.

**Comment by davisagli** [comment] 2015-04-08 01:27
This is a duplicate of #31

**Closed by davisagli** 2015-04-08 01:27 UTC
