### ISSUE TITLE
VMS: vms.wta.org My Backpack Login error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#535] opened 2016-01-12 01:51 UTC
When I go to vms.wta.org and click on My Backpack / Login I get directed to the URL:  http://127.0.0.1:6543/

Returns the Page can not be found error.

**Comment by cewing** [comment] 2016-01-12 01:52
This is a duplicate of the error reported in #534

**Comment by WaBirder57** [comment] 2016-01-12 01:53
Opps, thanks.  Elliott was quicker than me.  Sorry not to have checked first.

**Closed** 2016-01-12 01:52 UTC
Labels: Bug, Duplicate, High Priority, Plone, Pyramid, VMS BUDGET
