### ISSUE TITLE
ACL Only Work Party - Contact not flagged as ACL should not be allowed to register

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#124] opened 2015-06-03 00:16 UTC
A contact who is not an ACL ( based on field on contact record not being set True) can be registered for an "ACL only" work party through Salesforce.

Go to an "ACL Only" work party and add and register a contact who is not an ACL.  Select the Work Party Role of ACL.  Note that this person is now registered.  If the WP Role is set to Volunteer this is checked appropriately and the contact can not be registered.  Story #187, iteration #7

**Comment by mscholtz** [comment] 2015-06-11 19:55
@WaBirder57 so you're saying this person can be registered by staff in SF?  And it should prevent staff from doing so?

They can't register themselves for an ACL-only WP in VMS, right?

**Comment by WaBirder57** [comment] 2015-06-11 21:08
In VMS a volunteer who is not an ACL (as indicated by the field on SF Contact) can not register for an ACL only work party.  These ACL only WP's can't be

In Salesforce staff (no one) can add an volunteer to an ACL only WP if they are not an ACL, as indicated by the field on the SF Contact.

**Comment by mscholtz** [comment] 2015-06-11 22:17
OK, but trying to get clear on which part of this already works, and which part doesn't.

The VMS part works, SF part doesn't, correct?

**Comment by WaBirder57** [comment] 2015-06-11 22:56
Yes, this is a Salesforce issue.

**Comment by ecmnineta** [comment] 2015-06-17 18:02
@WaBirder57 I am not sure I know how to reproduce this. Here is what I did:
- I went to a WP that is an ACL Only WP
- Tried to register a volunteer and I got this error: Error: Only ACLs or CLs can be registered for this Work Party.
Could you describe the steps you took to register a volunteer for an ACL only party in SF or clarify if I am not understanding this ticket correctly?
Thanks,
N

**Comment by ninetaLogik** [comment] 2015-06-17 18:07
@WaBirder57 I am not sure I know how to reproduce this. Here is what I did:

    I went to a WP that is an ACL Only WP
    Tried to register a volunteer and I got this error: Error: Only ACLs or CLs can be registered for this Work Party. Could you describe the steps you took to register a volunteer for an ACL only party in SF or clarify if I am not understanding this ticket correctly? Thanks, N

**Comment by mscholtz** [comment] 2015-06-17 18:12
@ninetaLogik just to clarify: you took those steps in SF?  Or in VMS?

**Comment by ninetaLogik** [comment] 2015-06-17 18:14
In SF. But I don't think that's what Charlie meant. Maybe he is not referring to the WP Registration role of volunteer but the fact that the Contact we are trying to register has the CL or ACL flag checked. I will let him clarify.

**Comment by mscholtz** [comment] 2015-06-17 18:31
@ninetaLogik correct, Charlie is talking about a field on the contact, not on the registraiton (see original post).  

but @WaBirder57 we should make sure and clarify which field on contact should control this.  

There's the Assistant Crew Leader checkbox, which predates VMS and hasn't been worked into VMS at all AFAIK.  And then there's the VMS Permission Level picklist, where one possible value is "Assistant Crew Leader".

Do we still need the checkbox?  Does it provide something beyond what we get from the Permission Level field?

**Comment by ninetaLogik** [comment] 2015-06-17 18:41
Is this an accurate representation of what needs to be allowed vs not allowed? 
![wpreg roles](https://cloud.githubusercontent.com/assets/10534454/8215572/b905cf4a-14e5-11e5-8881-b641f687b0e7.PNG)

**Comment by WaBirder57** [comment] 2015-06-17 23:28
I don't think this is quite right.

When a Contact (ACL or CL) sign up for a work party the WP Reg ROLE will be ACL.  There is only one Registration record with ROLE CL (see field on WP for Leader).  Thus a Contact (ACL or CL) would never have the WP Reg ROLE = VOLUNTEER.  Thus the 2nd line on your first row should be ->NO in both columns.

For Contact (NOT ACL or CL) they could never be WP Reg ROLE = ACL, CL.  Thus the first line in the second row of your table would always have => NO.  The others are correct.

Let me know if you have more questions.

**Comment by davisagli** [comment] 2015-06-17 23:33
@WaBirder57 currently we display a dropdown on the registration form so a contact with VMS Permission Level = Assistant Crew Leader or Crew Leader can choose whether they want to be a Volunteer or ACL for a particular work party. What you just said suggests that we should remove that choice and always register contacts with these permission levels as ACLs. Is that correct?

**Comment by mscholtz** [comment] 2015-06-17 23:35
@davisagli @WaBirder57 Charlie, I remember you saying earlier that sometimes ACLs come to WPs as regular vols and don't perform ACL duties at that WP.  I think that's why that choice is in there

and @WaBirder57 we still need a response to my question above re the ACL checkbox vs the Permission Level field

**Comment by WaBirder57** [comment] 2015-06-17 23:52
HI all, Ok I stand corrected (checked in with Rebecca where they just discussed this today in staff meeting).  A Contact who is a CL or ACL can have WP Reg = VOLUNTEER.  Let me know if I need to update my prior comment on the table.

At this point we would like to keep both the ACL and CL check boxes (along with the date field) on the Contact.  For example there could be someone who has Staff permissions who is or isn't a CL or ACL.  What would happen if someone (say Elliot) who has VMS permissions as Staff signs up for a WP (and he is not a Contact ACL or CL)?

**Comment by mscholtz** [comment] 2015-06-18 00:05
@WaBirder57  Right now, AFAIK, VMS only looks at the VMS Permissions field.  And staff is the highest permission.  So it would allow Elliot to sign up as anything he wanted (i.e. ACL)  It assumes CLs are assigned in SF, so doesn't let them select that on VMS.  @davisagli correct me if I'm wrong.

If you want it to look at the checkboxes as well we'll need to start working that in.  But I'm not yet sure why we still need those..  Is it because of the dates?  We could conceivably keep those but ditch the checkboxes.

Would anyone ever be eligbile as CL but not an ACL?  
Would anyone ever be eligible as CL/ACL but not have permission to log in as such on VMS?

If the answer is no to both of those, not sure we need separate checkboxes here.

**Comment by mscholtz** [comment] 2015-06-18 00:07
@WaBirder57 and I guess the other question is: where else in your production SF are those checkboxes used now?  
I know they're used in StepUp, but that's easy to adjust.
I assume they're used in reports.
Anything else?  Is there any Workflow or other automation that depends on them?

**Comment by WaBirder57** [comment] 2015-06-18 00:13
They are used in some reports Rebecca said. No work flow or automation that
I know of.

Charlie

**Comment by mscholtz** [comment] 2015-06-18 00:17
It's your call, Charlie, but what I'm trying to avoid here is having redundant fields that mean the same thing.  Because then we can run into problems if you set one but forget to set the other.  

If we would never set Permission Level to ACL unless the ACL box was checked, then maybe we don't need both, because they effectively mean the same thing.

And I hear you on the staff thing, but I don't think that preventing staff from impersonating ACLs is really your big concern here, especially given they can log into SF and do most anything they want..

**Comment by WaBirder57** [comment] 2015-06-18 00:41
I agree that we don't want redundant information.   To me the check boxes
indicate if someone is qualified to work as an ACL or CL.   The VM
Permission field sets their VMS permission level when accessing the system
via the website.  Often these may be set to the same  value.  That is ACL
check box is true and VMS permission is ACL.

Charlie

**Comment by mscholtz** [comment] 2015-06-18 01:18
OK, let's assume for now that we keep both.   My questions would then be:

1. You would want VMS to require both the ACL checkbox *and* ACL-or-higher
permission level to register as ACL?

2. In SF, would you want staff to be prevented from registering someone as
ACL if there's no ACL checkbox for the contact?   But it wouldn't need any
particular VMS permission level?

3. Would we want want to require that the ACL checkbox be checked in order
to set someone to ACL permission level?






On Wed, Jun 17, 2015 at 5:41 PM, Charles Kahle <notifications@github.com>
wrote:

> I agree that we don't want redundant information. To me the check boxes
> indicate if someone is qualified to work as an ACL or CL. The VM
> Permission field sets their VMS permission level when accessing the system
> via the website. Often these may be set to the same value. That is ACL
> check box is true and VMS permission is ACL.
>
> Charlie
> On Jun 17, 2015 5:17 PM, "Matthew Scholtz" <notifications@github.com>
> wrote:
>
> > It's your call, Charlie, but what I'm trying to avoid here is having
> > redundant fields that mean the same thing. Because then we can run into
> > problems if you set one but forget to set the other.
> >
> > If we would never set Permission Level to ACL unless the ACL box was
> > checked, then maybe we don't need both, because they effectively mean the
> > same thing.
> >
> > And I hear you on the staff thing, but I don't think that preventing
> staff
> > from impersonating ACLs is really your big concern here, especially given
> > they can log into SF and do most anything they want..
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/washingtontrails/vms/issues/124#issuecomment-112984777>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/124#issuecomment-112995251>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by mscholtz** [comment] 2015-07-27 21:32
@WaBirder57 I think I'm still waiting on some answers to the above questions from you here.  Thanks!

**Comment by mscholtz** [comment] 2015-11-09 19:45
@ebskopin we never got some questions answered from Charlie on this one.  Can you look at my last Jun 17 comment and answer those 3 questions, or find answers somewhere?  Or if this needs to wait for Charlie's return please just let us know.  Thanks!

**Comment by ebskopin** [comment] 2015-12-01 20:35
Sorry, this got buried.  In answer to your questions, if we're keeping the two instances of ACL/CL distinction I would say:

1. Yes, to register on VMS you would need ACL checked and have at least ACL permission.
2. Yes, I would say that the ACL checkbox needs to be clicked but the permission level does not need to be ACL.
3. I would say no, there might be some instances where we want to grant someone access to VMS on the ACL permission level who is not an ACL.

Hopefully that is clear and isn't too contradictory.

**Comment by mscholtz** [comment] 2015-12-07 23:22
@ebskopin sounds OK, thanks!

@ninetaLogik reassigning this one back to you, after long last, now that we have clarity.  Let me know if you have any questions.

**Comment by ninetaLogik** [comment] 2015-12-09 16:28
@ebskopin I am wondering if this was re-tested recently. Here is the error message I am getting when registering (in Salesforce) someone whose Contact record is not marked as an (A)CL for a Work Party marked as "ACL Only": 

Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger WTA_VMS_WP_Registration caused an unexpected exception, contact your administrator: WTA_VMS_WP_Registration: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id a2eK00000000k0kIAA; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, The contact listed as Crew Leader is not eligible. Please mark the contact as an active Crew Leader, assign VMS crew leader permissions, then resave.: []: Class.WTA_VMS_WP_Registration_TriggerClass.setLeaderFieldOnWorkParty: line 422, column 1 

It's not a pretty error message but it's preventing me from registering the Contact until I actually go and mark their record as (A)CL (depending on the WPReg Role I am trying to assign them)

Before we make any changes could you please re-test and let me know if this is still not working as expected? 

Thanks,
N

**Comment by ebskopin** [comment] 2015-12-09 17:38
Hey Nineta,

I am unable to replicate the error that you are describing.  I'm still finding that, when registering a contact without (A)CL marked on their record, I am successful in signing them up for an ACL only WP (when marking their WP Role as ACL/CL). An error message DOES block me from doing so when I attempt to register them with a WP Role as Volunteer.

I have been testing on this WP, https://cs9.salesforce.com/a2eK0000000wLhj?newid=a2oK0000001FcwI, and was able to register multiple people who are not marked as (A)CL.

Hopefully that answers your question.  Let me know if you need further info.

Thanks,
Elliott

**Comment by ninetaLogik** [comment] 2015-12-09 17:52
@ebskopin So it looks like if you mark the WP Reg Role as Volunteer or Crew Leader you get an error message, but not for Role=Assistant Crew Leader.

**Comment by mscholtz** [comment] 2015-12-09 18:30
It shouldn't throw an error if role = volunteer, right?

On Wed, Dec 9, 2015 at 9:52 AM, ninetaLogik <notifications@github.com>
wrote:

> @ebskopin <https://github.com/ebskopin> So it looks like if you mark the
> WP Reg Role as Volunteer or Crew Leader you get an error message, but not
> for Role=Assistant Crew Leader.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/124#issuecomment-163338486>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ninetaLogik** [comment] 2015-12-09 18:39
@mscholtz are you saying that one should be able to register a NON A(CL) Contact with an "ACL Only" Work Party with a Role=Volunteer? That doesn't sound right to me, but you could be correct.
@ebskopin can you clarify please?

**Comment by mscholtz** [comment] 2015-12-09 18:45
Oh, my bad.  You're right.

On Wed, Dec 9, 2015 at 10:40 AM, ninetaLogik <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> are you saying that one should be
> able to register a NON A(CL) Contact with an "ACL Only" Work Party with a
> Role=Volunteer? That doesn't sound right to me, but you could be correct.
> @ebskopin <https://github.com/ebskopin> can you clarify please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/124#issuecomment-163352673>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by ebskopin** [comment] 2015-12-09 19:02
Nineta. Your observation is correct, that registrants with role = Vol or CL are not allowed to register. However, in just testing again I noticed that a normal Vol was also restricted when the role was set to ACL. When I changed that vol to an ACL I was successful in registering them for the ACL only WP. I'm guessing you just made a change, which looks great...

**Comment by ninetaLogik** [comment] 2015-12-09 20:05
@ebskopin would you be able to run through a few more combinations to confirm this is working correctly now, or can I assume that is? Please let me know. Thanks,
Nineta

**Comment by ebskopin** [comment] 2015-12-09 20:16
I tested a few more permutations and it looks great. Thanks.

**Closed by ebskopin** 2015-12-09 20:16 UTC
Labels: Med-High Priority, Medium Priority, Salesforce, VMS BUDGET
