### ISSUE TITLE
Email Template Links should use Dynamic Base URLs

### ISSUE THREAD

**Issue by drewpiston** [washingtontrails/vms#412] opened 2015-11-06 22:54 UTC
The Email Templates should use a base URL from custom settings for all links so that they are easier to change on deploy to prod.

**Comment by drewpiston** [comment] 2015-11-12 23:00
This is ready for review -- unfortunately it's a little hard to test. Best thing to do would be to send out one of each email template in this folder (https://cs9.salesforce.com/00X?setupid=CommunicationTemplatesEmail&fcf=00lK0000000nkT0) and make sure the links are correct.
You can send out a test email by clicking the "Sent Test and Verify Merge Fields" button on the email template and then selecting a matching Contact and WP_Registration from the popup window.

**Comment by ebskopin** [comment] 2015-12-07 19:39
tested, look good

**Comment by ebskopin** [comment] 2015-12-07 22:10
In re-testing these, the links at the bottom of each e-mail under "More Info" are not directing to active pages. Im wondering if this has something to do with the MBP deploy?

**Comment by davisagli** [comment] 2015-12-07 22:12
@ebskopin what's one of the URLs that's not working?

**Comment by ebskopin** [comment] 2015-12-08 17:49
![image](https://cloud.githubusercontent.com/assets/14843712/11663325/6fc8533c-9d90-11e5-9c3e-a35441073489.png)

The 3 links under more info are not working.  

The Manage Your Work Parties link directs here - https://cs9.salesforce.com/p/email/template/EmailTemplateEditorUi/http://staging.wta.org:6543

The Frequently Asked Questions here - http://mybackpack.wta.org/volunteer/volunteering/questions

And The Trail Work Guide here - http://mybackpack.wta.org/volunteer/about-trail-work-1/trail-work-guide/trail-work-guide

**Comment by drewpiston** [comment] 2015-12-09 21:04
The first one looks like a bug.

For the second and third, should those be pointing to "http://staging.wta.org/*" instead of  "http://mybackpack.wta.org/*"

**Comment by davisagli** [comment] 2015-12-09 21:11
Changing the base url to staging.wta.org should make this work since staging has a full copy of the site's data, unlike the mybackpack testing site.

**Comment by drewpiston** [comment] 2015-12-09 22:15
Right now for links I'm pulling one of these two base URLs in from Custom Settings:
1. VMS Base URL (http://staging.wta.org:6543)
2. Plone Base URL	(http://mybackpack.wta.org)

David, are you suggesting that we use the VMS Base URL instead of the Plone Base URL for FAQ and Trail Work Guide?  I've gotten a little confused about the difference between those two.

Thanks,
 Drew

**Comment by davisagli** [comment] 2015-12-09 22:20
No, VMS and Plone are two different systems that handle different things. The VMS URL is correct for now (we only have one copy of vms deployed). The Plone URL should change to http://staging.wta.org (no port, unlike the vms URL) and is what we should use for these links.

David Glick
(mobile)

**Comment by drewpiston** [comment] 2015-12-09 22:24
Thanks David, that makes more sense.

I've changed the Plone URL from http://mybackpack.wta.org to http://staging.wta.org, links seem to be working.

**Comment by ebskopin** [comment] 2015-12-09 23:27
Thanks @davisagli @drewpiston, links are working.

**Comment by ebskopin** [comment] 2015-12-09 23:54
Arg, spoke a little too soon and found a few issues.

For the "VMS Waitlisted Confirmation Email - Day Work Party" template the links marked in red (see below) point to an incorrect link:

![image](https://cloud.githubusercontent.com/assets/14843712/11702560/76a0dfc4-9e8c-11e5-8931-cbaf61dc747b.png)

This links are, respectively: 
https://cs9.salesforce.com/email/http://staging.wta.org/volunteer/about-trail-work-1/trail-work-guide/trail-work-guide
https://cs9.salesforce.com/email/http://staging.wta.org/volunteer/about-trail-work-1/trail-work-guide/trail-work-guide
https://cs9.salesforce.com/email/http://staging.wta.org/volunteer/about-trail-work-1/trail-work-guide/trail-work-guide

The only other thing I'm noticing is on the "VMS WP Notification of Open Spot":

![image](https://cloud.githubusercontent.com/assets/14843712/11702612/ec307bbe-9e8c-11e5-9964-96b78c83f9fc.png)

These two links prompt the same error when clicked:  {"code": 500, "detail": "u''", "title": "KeyError"}

Otherwise, all of the other links on the other e-mails are tested and confirmed as functional.

**Comment by davisagli** [comment] 2015-12-09 23:56
What URLs do the broken links in the VMS WP Notification of Open Spot go to?

**Comment by ebskopin** [comment] 2015-12-09 23:59
They both go here when clicked, respectively: 

![image](https://cloud.githubusercontent.com/assets/14843712/11702715/b653691a-9e8d-11e5-911d-ad63ac5a43e2.png)

![image](https://cloud.githubusercontent.com/assets/14843712/11702740/d31ef032-9e8d-11e5-9207-f9a7351f3c29.png)

**Comment by davisagli** [comment] 2015-12-10 00:05
The problem there is that there's no registration id passed in the URL -- it should have r=SOMETHING not just r=

**Comment by ebskopin** [comment] 2015-12-11 00:13
I received a similar error when clicking on the accept link in relation to some different testing:

![image](https://cloud.githubusercontent.com/assets/14843712/11732431/f9fd7068-9f58-11e5-99fd-123fb864d30b.png)

**Comment by davisagli** [comment] 2015-12-11 00:25
It may be formatted similarly but that's a different error. Can you put it in a new ticket with more info about what you were doing?

David Glick
(mobile)

**Comment by drewpiston** [comment] 2015-12-11 22:32
Thanks @ebskopin -- I fixed the broken links in VMS Waitlisted Confirmation Email - Day Work Party. Trail Work Guide resulted in an error for me but it's no longer the bad Salesforce URL, and I think it's a data issue for that particular work party.

**Comment by ebskopin** [comment] 2015-12-11 23:13
Thanks. Looks good. Closing this as #489 covers the other item.

**Closed by ebskopin** 2015-12-11 23:13 UTC
Labels: High Priority, Reviewing, Salesforce, VMS BUDGET
